language: node_js
node_js:
- '4'
before_install:
- npm install coveralls
- npm install istanbul
install: npm install
script: npm run-script coveralls && cd web && npm install && npm test
notifications:
  slack:
    secure: dQo216s03gwSGZMBKFKfjysx2Gmchrj44l5fc5qji1/QU6HDTXDZjRjY7nqHMRaf8rxtK0Aau76dVo0NmIjbtTjEnprdEs6lEUi0tgbup4MtF0lh8mz9bcw3le51QKQPcOONH1pfiMGeKubafso2PnsyjacSVmnPTBk+FObKDpkLvppoMweT1N0bu+xc8tzOVnIAi4ywGRjt/E+Hrd/FzXTjUXcP0g0hBwczESrIgKklfguTsZQ8qKcVcc1lFeFQHjReaXq+ONypecPB6BIi0jovbkNHd+SQqvSthn8sZVPZ5gecG+fVxF738ZRrnD2+VBNHqdtX4Jyeao2HLjebCPIJV2TYmQz2YAXAOdmPtlakTF0AFmJY7wwOImjugzYemlFhJqcJz+fsBzQxvo5a9I2pvaPoJFuZq/DCYfMjuG1XM7URcjbLT3th/PjJDf9ri9lO6Pen8VIV0hpAhM4oSSF4u49ZbArucumrYwy9iykZUtQicEYmjrEgaMJpVFQZErtWKaOT79iLrAzXLzCfHZRLo5aCUM9xaGBjT7oMnbl5MJ97lJ1ouu8vOv7/xKd3jf2R/kwUngTgR+Cs1OJaRNaUR64ZbxjeqoIZltGgFtlM+PIBZljchwxHZQ8fmV7FY7D3F8MlSFDxlwaW6wSZjuC6xB2KZhFnG5FkfQezwp8=

